import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/ui/navbar/navigation";
import BootstrapClient from "@/components/bootstrap-import/bootstrap-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
